### ISSUE TITLE
Missing dist files in latest release

### ISSUE THREAD

**Issue by janvorisek** [escape-llc/pdf-component-vue#21]
Dist folder is missing in the `0.2.0` release on npm. Version `0.1.0` works fine.

**Comment by escape-llc** [comment]
thanks for the follow-up we will look into it.

**Comment by escape-llc** [comment]
Such a terrible mistake! apparently `npm publish` takes whatever files were laying around (or not) in the `dist` folder.

Please try `0.3.0` it also has the new resize functionality in there.
![image](https://github.com/escape-llc/pdf-component-vue/assets/3513926/37243ece-67bd-4981-9c8a-d8fbcf860e2d)
