### ISSUE TITLE
CSS Containment

### ISSUE THREAD

**Issue by escape-llc** [escape-llc/pdf-component-vue#35]
Look into using the CSS Containment to enhance rendering information for the browser.

`content-intrinsic-size` et al.

https://infrequently.org/2020/12/resize-resilient-deferred-rendering

The easiest way to handle this is to defer to the user of the component; they should include the `contain: content` CSS for the `pageContainer` property.

**Comment by pyramid-johng** [comment]
More info here https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_containment
