### ISSUE TITLE
Pages repeat with textLayer enabled

### ISSUE THREAD

**Issue by micos7** [escape-llc/pdf-component-vue#38]
So when `textLayer` is  enabled i get duplicate pages scrolling: one image followed by the same page in text (selectable) .What am I missing? Thanks.

**Comment by escape-llc** [comment]
More information please, but it sounds like your CSS is off.  It must be configured so the layers "stack" please see the demo application for how to set this up.
![image](https://github.com/escape-llc/pdf-component-vue/assets/3513926/3b5a9ec5-f0c5-4f7f-8b45-13c1a21fe1e5)

As you can see everything in the demo app lines up; please consult the CSS for details they all use the identical technique.

![image](https://github.com/escape-llc/pdf-component-vue/assets/3513926/ff9eb5e0-cbe6-47ca-9deb-734e24e1ac95)

Here is the "stack" style from demo 1:

```
:deep(.page-stack) {
	grid-area: 1 / 1 / 1 / 1 !important;
	box-sizing: border-box;
	background: transparent;
	width:100%;
}

```

And here is the props for the component you must configure the `canvasClass`/`textLayerClass`/`annotationLayerClass` props

```
	<PdfComponent
		id="my-pdf"
		class="document-container"
		:textLayer="true"
		:annotationLayer="true"
		pageContainerClass="page-container"
		canvasClass="page-stack"
		annotationLayerClass="page-stack"
		textLayerClass="page-stack"
		@loaded="handleLoaded"
		@load-failed="handleError"
		@rendered="handlePageRendered"
		@render-failed="handleRenderingFailed"
		:source="url">
		<template #pre-page="slotProps">
			<div style="text-align:center" :style="{ 'grid-row': slotProps.gridRow, 'grid-column': slotProps.gridColumn }">Page {{slotProps.pageNumber}}</div>
		</template>
	</PdfComponent>

```

**Comment by escape-llc** [comment]
We tried incorporating this into our demo app, but it appears to be some stuff missing; are you packaging this into a component?  If so, please provide the "view" where you are deploying this, as we cannot get it to run by itself.

Alternatively, please augment the gist to include that component; or do you have a repository we can look at?

**Comment by micos7** [comment]
[Try it in another browser if it freezes](https://codesandbox.io/p/sandbox/keen-raman-vst7zd?file=%2Fsrc%2Fcomponents%2FHelloWorld.vue&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clplo6dj300072068r27ug86z%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clplo6dj300032068dnp4m26c%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clplo6dj300042068phrvkoff%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clplo6dmr000j20689orglg0c%2522%257D%252C%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clplo6dj3000620689j20wrq3%2522%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clplo6dmr000j20689orglg0c%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522SANDBOX_ONBOARDING%2522%252C%2522id%2522%253A%2522sandbox-onboarding%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522id%2522%253A%2522clplo6dmr000j20689orglg0c%2522%252C%2522activeTabId%2522%253A%2522sandbox-onboarding%2522%257D%252C%2522clplo6dj300032068dnp4m26c%2522%253A%257B%2522id%2522%253A%2522clplo6dj300032068dnp4m26c%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clplo6dj3000620689j20wrq3%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clplo6dj300052068dz3ez0am%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clplo6dj3000620689j20wrq3%2522%252C%2522activeTabId%2522%253A%2522clplo6dj300052068dz3ez0am%2522%257D%252C%2522clplo6dj300042068phrvkoff%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clplo6dj300042068phrvkoff%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by escape-llc** [comment]
Thanks for the submission.  I was able to troubleshoot your component.  There were these issues:

- use `style scoped`
- the prop for page container class was wrong; it should read `pageContainerClass="page-container"`
  - the name of prop was incorrect, and the CSS style was incorrect.  this prop must name a CSS style similar to `:class`

**Comment by escape-llc** [comment]
Sorry missed the calculated part you really want this `:pageContainerClass="pageContainer"` so it invokes the function note the addition of `:` for binding.

Thanks for providing an example using Composition API!
