### ISSUE TITLE
Allowing to zoom, showing a subpart of page?

### ISSUE THREAD

**Issue by twitwi** [escape-llc/pdf-component-vue#43]
Thanks for the component.
I haven't seen in any demos a way to zoom on a page (showing just a part of the page).
What would be a good approach to do this using pdf-component-vue? or maybe it is outside the scope of the library?

**Comment by escape-llc** [comment]
That is not currently a specific feature, but you could certainly access the `canvas` element of a page element at whatever scale you want, and copy the region of interest.

Alternatively you could create a "container" element to act as viewport on an instance of the component and use the overflow and translatex and translatey to reveal the desired region of interest.

**Comment by twitwi** [comment]
Ok thank you for the suggestions, I might go with one of these.
I was hoping for a solution that would not involve rendering the whole page (which would need a huge canvas for high zooms) but it's good to know it is not currently in pdf-component-vue, so I'll be closing the issue.

**Comment by escape-llc** [comment]
Please stay tuned we are not ruling out anything in the future...

**Comment by escape-llc** [comment]
Thought about this some more, and you could use technique in the `PrintCommand` in `Commands.js` to do custom rendering of any page you wish, as the `CommandExecuteContext` gives you direct access to the `pdfjs` page.  At this point you have all techniques available to you to render that however to a `canvas` you control.

**Comment by twitwi** [comment]
Thanks for the architectural insight. I won't be able to try it in the short term (for now I can live with a no-zoom situation), but surely at some point.
