### ISSUE TITLE
 The server responded with a status of 431 (Request Header Fields Too Large)

### ISSUE THREAD

**Issue by micos7** [escape-llc/pdf-component-vue#53]
After update to 0.6  I get 

handle.load-error Error: Setting up fake worker failed: "Cannot load script at:  Failed to load resource: the server responded with a status of 431 (Request Header Fields Too Large).

![image](https://github.com/escape-llc/pdf-component-vue/assets/4460809/d2be443f-41a4-4176-b9f9-dfe4995ff5ae)

Cleared cache and cookies,still the same.

 On 0.5 it was smooth sailing, thank you for your work.

**Comment by escape-llc** [comment]
Next package `0.7.0` will no longer contain any `pdfjs-dist` so please try again when that comes out.
